name = "r6m-news-worker"
main = "worker.js"
compatibility_date = "2026-04-02"

[[kv_namespaces]]
binding = "NEWS_STATE"
id = "8f4b5c089e954039a286eabaa78d365a"

# Keep secrets in the Cloudflare dashboard.
